"""Profiling primitives for engine and GPU telemetry."""

from .nvml_session import GPUSample, NVMLSample, NVMLSession, summarize_nvml_samples
from .prometheus import (
    COUNTER_METRICS,
    GAUGE_METRICS,
    HISTOGRAM_METRICS,
    VLLM_METRIC_ALIASES,
    PrometheusClient,
    PrometheusCollector,
    PrometheusMetricsParser,
    PrometheusParser,
    PrometheusSample,
    PrometheusSnapshot,
    canonicalize_vllm_metrics,
    histogram_quantile,
    parse_prometheus_text,
    parse_vllm_metrics,
    summarize_prometheus_snapshots,
)
from .session import TelemetryFrame, TelemetrySession
from .timeseries import (
    JSONLWriter,
    SampleTimestamp,
    capture_timestamp,
    counter_window_delta,
    integrate_power_samples,
    percentile,
    summarize_values,
    write_jsonl,
)

__all__ = [
    "COUNTER_METRICS",
    "GAUGE_METRICS",
    "GPUSample",
    "HISTOGRAM_METRICS",
    "JSONLWriter",
    "NVMLSample",
    "NVMLSession",
    "PrometheusClient",
    "PrometheusCollector",
    "PrometheusMetricsParser",
    "PrometheusParser",
    "PrometheusSample",
    "PrometheusSnapshot",
    "SampleTimestamp",
    "TelemetryFrame",
    "TelemetrySession",
    "VLLM_METRIC_ALIASES",
    "canonicalize_vllm_metrics",
    "capture_timestamp",
    "counter_window_delta",
    "histogram_quantile",
    "integrate_power_samples",
    "parse_prometheus_text",
    "parse_vllm_metrics",
    "percentile",
    "summarize_nvml_samples",
    "summarize_prometheus_snapshots",
    "summarize_values",
    "write_jsonl",
]
